#!/bin/bash

REAL_PWD="$(realpath "$PWD")"
MOUNTED_DIR="/${REAL_PWD##*/}"
PI_HOME="/pi-home"

exec docker run --rm -it \
  --user $(id -u):$(id -g) \
  -e "MISE_CEILING_PATHS=$MOUNTED_DIR" \
  -e "HOME=$PI_HOME" \
  -v "packages:/pi-home/.pi/packages" \
  -v "$HOME/.agents:$PI_HOME/.agents" \
  -v "$HOME/.pi/agent:$PI_HOME/.pi/agent" \
  -v "$HOME/.gitconfig:$PI_HOME/.gitconfig:ro" \
  -v "$HOME/.gitignore_global:$PI_HOME/.gitignore_global:ro" \
  -v "$REAL_PWD:$MOUNTED_DIR" \
  -w "$MOUNTED_DIR" \
  pi-docker:latest
